config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  
  resources :users, only: [:index, :show]  do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define User abilities
    return unless user.is? :admin

    can :destroy, Post
    can :destroy, Comment

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter
  after_destroy :update_post_comments_counter

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter
  after_destroy :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  def initialize(attributes = {})
    super
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[admin user].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def initialize(attributes = {})
    super
    self.posts_counter ||= 0
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post_id = @post.id
    if @comment.save
      flash[:success] = 'Comment created successfully'
    else
      flash[:danger] = "Couldn't create comment"
    end
    redirect_to "/users/#{current_user.id}/posts/#{params[:post_id]}"
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    flash[:success] = 'Comment successfully deleted'
    redirect_to "/users/#{current_user.id}/posts/#{params[:post_id]}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(author: @user, post: @post)
    @like.save
    flash[:success] = 'Liked successfully!'
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @user = User.includes(:posts, :comments).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to "/users/#{current_user.id}/posts"
    else
      flash[:danger] = "Couldn't create post"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    flash[:success] = 'Post successfully deleted'
    redirect_to "/users/#{current_user.id}/posts"
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(created_at: :asc)
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<ul class="ul-box">
  <li class="li-box">
    <h3 class="form-head">Add a comment</h3>
    <%= form_with(model: @comment, url: user_post_comments_path(@post), local: true) do |form| %>
      <div>
        <%= form.text_area :text, placeholder: "Enter your comment", class: "form-text-area" %>
      </div>
      <%= form.submit "Add Comment", class: "button form-button" %>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/ad432cd04f.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav>
      <ul class="ul-box navbar">
        <li>
          <% if current_user %>
            <a class="nav-home" href="/users">Home</a>
          <% end %>
        </li>
        <li>
          <ul>
            <li>
              <div class="dropdown">
                <button class="dropbtn">
                  Account <i class="fa-solid fa-chevron-down"></i>
                </button>
                <div class="dropdown-content">
                  <% if current_user %>
                    <%= link_to "Edit Account", edit_user_registration_path %>
                    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
                  <% else %>
                    <%= link_to "Sign Up", new_user_registration_path %>
                    <%= link_to "Sign In", new_user_session_path %>
                  <% end %>
                <div>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<ul class="ul-box">
  <li class="user-details">
    <div class="image-box">
      <%= image_tag(@user.photo || "", class: "user-image") %>
    </div>
    <div class="info-box">
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </li>

  <li>
    <ul class="posts-box">
      <% @user.posts.each do |post| %>
        <li class="li-box">
          <div class="inner-li-box">
            <a href=<%= "/users/#{@user.id}/posts/#{post.id}" %> >
              <h3><%= post.title %></h3>
              <p class="p_tags"><%= post.text %></p>
              <div class="comments_n_likes">
                <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
              </div>
            </a>
          </div>
        </li>
        <li class="li-box comment-box">
          <div class="inner-li-box">
            <% if post.recent_comments.blank? %>
              <p class="each_comment">No comments available.</p>
            <% else %>
              <% post.recent_comments.each do |comment| %>
                <p class="each_comment">
                  <strong><%= comment.author.name %>:</strong>
                  <%= comment.text %>
                </p>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </li>
  <li class="user-details pagination pagination-box">
    <% @user.posts.each_with_index do |post, post_idx| %>
      <%= link_to user_post_path(@user, post) do %>
        <button class="pagination-button"><%= post_idx + 1 %></button>
      <% end %>
    <% end %>
  </li>
</ul>

app/views/posts/new.html.erb
<ul class="ul-box">
  <li class="li-box">
    <h2>Create a New Post</h2>
  </li>
  <li class="li-box">
    <%= form_with model: @post, url: user_posts_path do |form| %>
      <div>
        <%= form.text_field :title, placeholder: 'Enter title', required: true, class: 'form-input' %>
      </div>
      <div>
        <%= form.text_area :text, placeholder: 'Enter Post Text', required: true, class: 'form-text-area' %>
      </div>
      <%= form.submit "Create Post", class: "button form-button" %>
    <% end %>
  </li>
</ul>

app/views/posts/show.html.erb
<ul class="ul-box">
  <li>
    <ul class="posts-box">
      <li class="li-box">
        <div class="inner-li-box">
          <div class="title_n_comments">
            <h4><%= @post.title %> by <%= @user.name %></h4>
            <p>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
          </div>
          <p class="p_tags post_text"><%= @post.text %></p>
          <div>
            <%= form_with model: @like, url: user_post_likes_path(@user, @post) do |form|%>
                <%= form.submit 'Like post', class: 'button like-button' %>
            <% end %>
          </div>
          <% if (can? :destroy, Post) || current_user.id == @post.author_id %>
            <div>
              <%= button_to "Delete Post", user_post_path(@user, @post), method: :delete %>
            </div>
          <% end %>
        </div>
      </li>
      <li class="li-box comment-box">
        <div class="inner-li-box">
          <% if @post.comments.blank? %>
            <p class="each_comment post_show_comment">No comments available.</p>
          <% else %>
            <% @post.comments.each do |comment| %>
              <p class="each_comment post_show_comment">
                <strong><%= comment.author.name %>:</strong>
                <%= comment.text %>
              </p>
              <% if (can? :destroy, Comment) || current_user.id == comment.author_id %>
                <div>
                  <%= button_to "Delete Comment", user_post_comment_path(@user, @post, comment), method: :delete %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
  </li>
  <li class="li-box">
    <a href="<%= url_for(new_user_post_comment_path(@user, @post)) %>" class="button button-wide">Add Comment</a>
  </li>
</ul>

app/views/users/index.html.erb
<% if @users.blank? %>
  <div class="li-box">
    <p class="p_tags inner-li-box">There are no users available.</p>
  </div>
<% else %>
  <ul class="ul-box">
    <% @users.each do |user| %>
      <li class="user-details">
        <div class="image-box">
          <a href="<%= url_for(user_path(user)) %>" >
            <%= image_tag(user.photo || "", class: "user-image") %>
          </a>
        </div>
        <div class="info-box">
          <a href="<%= url_for(user_path(user)) %>" >
            <h2><%= user.name %></h2>
            <p>Number of posts: <%= user.posts_counter %></p>
          </a>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<ul class="ul-box">
  <li class="user-details">
    <div class="image-box">
      <%= image_tag(@user.photo || "", class: "user-image") %>
    </div>
    <div class="info-box">
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </li>
  <li class="li-box">
    <div class="inner-li-box">
      <h2>Bio</h2>
      <p class="p_tags"> <%= @user.bio %> </p>
    </div>
  </li>
  <li>
    <h2 class="single-header">Posts</h2>
    <% if @user.recent_posts.blank? %>
      <div class="li-box">
        <p class="p_tags inner-li-box">There are no posts available.</p>
      </div>
    <% else %>
      <ul class="posts-box">
        <% @user.recent_posts.each do |post| %>
          <li class="li-box">
            <div class="inner-li-box">
              <h3>Post #<%= post.id %></h3>
              <p class="p_tags"><%= post.text %></p>
              <div class="comments_n_likes">
                <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="button_div">
        <a href="<%= url_for(user_posts_path(@user)) %>" class="button">See all posts</a>
      </div>
    <% end %>
  </li>
  
  <% if current_user.id == @user.id %>
    <li class="li-box">
      <a href="<%= url_for(new_user_post_path(@user)) %>" class="button button-wide">Create new post</a>
    </li>
  <% end %>
</ul>